In [1]:
import pandas as pd
import numpy as np
df =pd.read_csv("train.csv")

In [2]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94
2,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
3,6,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86
4,11,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184

In [3]:
df_extract = df[["Order ID", "Category"]]

In [4]:
gender_probs = {

    "Furniture": {"Female": 0.62, "Male": 0.38},

    "Technology": {"Male": 0.76, "Female": 0.24},

    "Office Supplies": {"Female": 0.73, "Male": 0.27}

}



# Assign gender based on probabilities

def assign_gender(category):

    probs = gender_probs[category]

    return np.random.choice(list(probs.keys()), p=list(probs.values()))



df["Gender"] = df["Category"].apply(assign_gender)

In [5]:
# Young adult (18-25 age), Adult (26-44 age), Middle-age (45-59 age), Old age (60 age) 
age_group_probs = {

    "Furniture": {"Young adult": 0.12, "Adult": 0.24,"Middle-age":0.42, "Old age":0.22},

    "Technology": {"Young adult": 0.38, "Adult": 0.31,"Middle-age":0.18, "Old age":0.13},

    "Office Supplies": {"Young adult": 0.18, "Adult": 0.32,"Middle-age":0.28, "Old age":0.22}

}



# Assign gender based on probabilities

def assign_age_group(category):

    probs = age_group_probs[category]

    return np.random.choice(list(probs.keys()), p=list(probs.values()))



df["Age Group"] = df["Category"].apply(assign_age_group)

In [6]:
# Young adult (18-25 age), Adult (26-44 age), Middle-age (45-59 age), Old age (60 age) 
cancel_probs = {

    "South": {"Return": 0.01, "Received": 0.99},

    "West": {"Return": 0.1, "Received": 0.9},

    "East": {"Return": 0.02, "Received": 0.98},
    
    "Central":{"Return": 0.03, "Received": 0.97}
}



# Assign gender based on probabilities

def assign_cancel_probs(category):

    probs = cancel_probs[category]

    return np.random.choice(list(probs.keys()), p=list(probs.values()))



df["Status"] = df["Region"].apply(assign_cancel_probs)

In [7]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Gender,Age Group,Status
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,Female,Old age,Received
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,Female,Old age,Received
2,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,Female,Adult,Received
3,6,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,Male,Middle-age,Received
4,11,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,Female,Young adult,Received

In [8]:
# Convert 'Order Date' to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)

# Sort by 'Order Date'
df = df.sort_values('Order Date').reset_index(drop=True)

# Create a probability of "Online" increasing over time
df['Online Probability'] = np.linspace(0.1, 0.5, len(df))

# Assign "Online" or "Offline" based on the probability
df['Order Type'] = df['Online Probability'].apply(lambda x: 'Online' if np.random.rand() < x else 'Offline')

# Drop the 'Online Probability' column if not needed
df = df.drop(columns=['Online Probability'])

In [9]:
# Convert 'Order Date' to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)

# Sort by 'Order Date'
df = df.sort_values('Order Date').reset_index(drop=True)

# Create a probability of "Online" increasing over time
df['Payment Probability'] = np.linspace(0.3, 0.7, len(df))

# Assign "Online" or "Offline" based on the probability
df['Payment Type'] = df['Payment Probability'].apply(lambda x: 'E-money' if np.random.rand() < x else 'Cash')

# Drop the 'Online Probability' column if not needed
df = df.drop(columns=['Payment Probability'])

In [10]:
df.to_csv("Superstore.csv", index=False)